from datetime import datetime
from dataclasses import dataclass
from typing import Optional

@dataclass
class Report:
    """Data structure for a complete business report"""
    
    business_goal: str
    plan_output: str
    ceo_output: str
    research_output: str
    analyst_output: str
    critic_output: str
    qa_output: str
    timestamp: str = None
    
    def __post_init__(self):
        if self.timestamp is None:
            self.timestamp = datetime.now().isoformat()
    
    def to_markdown(self):
        """Convert report to Markdown format"""
        
        md = f"""# AI Organization OS - Executive Report

**Generated:** {self.timestamp}

---

## Business Goal

{self.business_goal}

---

## Executive Summary

{self.qa_output[:500]}...

[Full QA Report Below]

---

## Strategic Planning Phase

### Execution Plan
{self.plan_output}

---

### CEO Strategy
{self.ceo_output}

---

## Analysis Phase

### Market Research
{self.research_output}

---

### Business Analysis
{self.analyst_output}

---

## Validation Phase

### Critical Review
{self.critic_output}

---

### Quality Assurance Report
{self.qa_output}

---

## Report Metadata

- **Generated:** {self.timestamp}
- **System:** AI Organization OS
- **Agents:** Planner, CEO, Research, Analyst, Critic, QA
- **Status:** Complete

---

*This report was generated by an AI multi-agent system. All recommendations should be reviewed by domain experts.*
"""
        
        return md
    
    def to_text(self):
        """Convert report to plain text format"""
        
        text = f"""{'='*80}
AI ORGANIZATION OS - EXECUTIVE REPORT
{'='*80}

Generated: {self.timestamp}

{'='*80}
BUSINESS GOAL
{'='*80}

{self.business_goal}

{'='*80}
EXECUTIVE SUMMARY (from QA Agent)
{'='*80}

{self.qa_output}

{'='*80}
PLANNING PHASE
{'='*80}

{self.plan_output}

{'='*80}
STRATEGIC PHASE
{'='*80}

{self.ceo_output}

{'='*80}
RESEARCH PHASE
{'='*80}

{self.research_output}

{'='*80}
ANALYSIS PHASE
{'='*80}

{self.analyst_output}

{'='*80}
VALIDATION PHASE
{'='*80}

{self.critic_output}

{'='*80}
END OF REPORT
{'='*80}

Report generated by AI Organization OS
All recommendations should be reviewed by domain experts.
"""
        
        return text
    
    def to_html(self):
        """Convert report to HTML format"""
        
        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>AI Organization OS Report</title>
    <style>
        body {{
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 1000px;
            margin: 0 auto;
            padding: 20px;
            background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
        }}
        .header {{
            background: linear-gradient(135deg, #0f2027, #203a43, #2c5364);
            color: white;
            padding: 40px;
            border-radius: 10px;
            margin-bottom: 30px;
        }}
        .header h1 {{
            margin: 0;
            font-size: 2.5em;
        }}
        .header p {{
            margin: 10px 0 0 0;
            opacity: 0.9;
        }}
        .section {{
            background: white;
            padding: 25px;
            margin: 20px 0;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
            border-left: 5px solid #00c6ff;
        }}
        .section h2 {{
            color: #0f2027;
            border-bottom: 2px solid #00c6ff;
            padding-bottom: 10px;
            margin-top: 0;
        }}
        .section h3 {{
            color: #203a43;
        }}
        .metadata {{
            background: #f9f9f9;
            padding: 15px;
            border-radius: 5px;
            margin-top: 20px;
            font-size: 0.9em;
        }}
        .footer {{
            text-align: center;
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            color: #666;
            font-size: 0.9em;
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>🧠 AI Organization OS</h1>
        <h2>Executive Business Report</h2>
        <p>Generated: {self.timestamp}</p>
    </div>

    <div class="section">
        <h2>Business Goal</h2>
        <p>{self.business_goal}</p>
    </div>

    <div class="section">
        <h2>Executive Summary</h2>
        <p>{self.qa_output.replace(chr(10), '<br>')}</p>
    </div>

    <div class="section">
        <h2>Execution Plan</h2>
        <p>{self.plan_output.replace(chr(10), '<br>')}</p>
    </div>

    <div class="section">
        <h2>Strategic Direction (CEO)</h2>
        <p>{self.ceo_output.replace(chr(10), '<br>')}</p>
    </div>

    <div class="section">
        <h2>Market Research Findings</h2>
        <p>{self.research_output.replace(chr(10), '<br>')}</p>
    </div>

    <div class="section">
        <h2>Business Analysis</h2>
        <p>{self.analyst_output.replace(chr(10), '<br>')}</p>
    </div>

    <div class="section">
        <h2>Critical Review</h2>
        <p>{self.critic_output.replace(chr(10), '<br>')}</p>
    </div>

    <div class="section">
        <h2>Quality Assurance</h2>
        <p>{self.qa_output.replace(chr(10), '<br>')}</p>
    </div>

    <div class="metadata">
        <p><strong>System:</strong> AI Organization OS</p>
        <p><strong>Generated:</strong> {self.timestamp}</p>
        <p><strong>Agents:</strong> Planner, CEO, Research, Analyst, Critic, QA</p>
        <p><strong>Embeddings:</strong> Sentence Transformers (all-MiniLM-L6-v2)</p>
        <p><strong>LLM:</strong> Groq Llama 3.3 70B</p>
    </div>

    <div class="footer">
        <p>This report was generated by an AI multi-agent system.</p>
        <p>All recommendations should be reviewed and validated by domain experts.</p>
        <p>© 2024 AI Organization OS. All rights reserved.</p>
    </div>
</body>
</html>"""
        
        return html


def create_report(workflow_result: dict):
    """
    Create a Report object from workflow execution result.
    
    Args:
        workflow_result: Output from graph.invoke()
        
    Returns:
        Report object
    """
    
    return Report(
        business_goal=workflow_result.get("user_goal", "Not specified"),
        plan_output=workflow_result.get("plan", "No plan generated"),
        ceo_output=workflow_result.get("strategy", "No strategy generated"),
        research_output=workflow_result.get("research", "No research conducted"),
        analyst_output=workflow_result.get("analyst_output", "No analysis generated"),
        critic_output=workflow_result.get("critic_output", "No critique generated"),
        qa_output=workflow_result.get("qa_output", "No QA review conducted"),
    )
